---
- apt:
    name: dhcpcd5
    update_cache: yes
  become: true

- template:
    src: dhcpcd.conf.j2
    dest: /etc/dhcpcd.conf
    owner: root
    group: netdev
    mode: "u=rw,g=rw,o=r"
  notify: restart dhcpcd
  become: true


- service:
    name: dhcpcd
    enabled: yes
  become: true
