---
- lineinfile:
    dest: /etc/fstab
    line: 'tmpfs    /tmp        tmpfs    defaults,noatime,nosuid,size=50m    0 0'
#  notify: mount tmp
- lineinfile:
    dest: /etc/fstab
    line: 'tmpfs    /var/tmp    tmpfs    defaults,noatime,nosuid,size=50m    0 0'
#  notify: mount var tmp
- lineinfile:
    dest: /etc/fstab
    line: 'tmpfs    /var/log    tmpfs    defaults,noatime,nosuid,mode=0755,size=100m    0 0'
#  notify: mount var log
- lineinfile:
    dest: /etc/fstab
    line: 'tmpfs    /var/run    tmpfs    defaults,noatime,nosuid,mode=0755,size=50m    0 0'
#  notify: mount var run
#tmpfs    /var/spool/mqueue    tmpfs    defaults,noatime,nosuid,mode=0700,gid=12,size=30m    0 0

- name: mount tmp
  mount:
    name: tmp
    src: /tmp
    fstype: tmpfs
    state: mounted
  become: true

- name: mount var tmp
  mount:
    name: var_tmp
    src: /var/tmp
    fstype: tmpfs
    state: mounted
  become: true

- name: mount var log
  mount:
    name: var_log
    src: /var/log
    fstype: tmpfs
    state: mounted
  become: true

- name: mount var run
  mount:
    name: var_run
    src: /var/run
    fstype: tmpfs
    state: mounted
  become: true
