---
- name: /tmp in tmpfs
  mount:
    name: /tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noatime,nosuid,size=50m
    state: present
  tags: fstab
  become: true

- name: /var/tmp in tmpfs
  mount:
    name: /var/tmp
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noatime,nosuid,size=50m
    state: present
  tags: fstab
  become: true

- name: /var/log in tmpfs
  mount:
    name: /var/log
    src: tmpfs
    fstype: tmpfs
    opts: defaults,noatime,nosuid,mode=0755,size=100m
    state: present
  tags: fstab
  become: true

# Apparently useless because :
#root@raspbian:~# ls /var/run -Al
#lrwxrwxrwx 1 root root 4 May 27  2016 /var/run -> /run
#
# - name: /var/run in tmpfs
#   mount:
#     name: /var/run
#     src: tmpfs
#     fstype: tmpfs
#     opts: defaults,noatime,nosuid,mode=0755,size=50m
#     state: present
  #tags: fstab
  #become: true
